hauler_store_path: /home/deathstar/hauler
rancher_version: v2.7.9
cert_manager_version: v1.13.2
additional_charts:
  - name: loki
    version: 2.8.3
    repo_url: https://grafana.github.io/helm-charts
  - name: consul
    version: 0.39.0
    repo_url: https://helm.releases.hashicorp.com
  - name: vault
    version: 0.25.0
    repo_url: https://helm.releases.hashicorp.com
  - name: neuvector
    version: 102.0.5+up2.6.4
    repo_url: https://charts.rancher.io