rancher_version: v2.9.1
cert_manager_version: v1.13.2
hauler:
  host: 10.10.0.50
  store_path: /tmp/hauler            #! this is just a local place to store cached store data
  archive_path: $PWD/hauler.tar.zst  #! this file will be one of the artifact copied into your airgap
harvester:
  version: v1.3.2

additional_charts:
  - name: rancher
    repo_url: https://rancherfederal.github.io/carbide-charts
    version: 2.9.1
  - name: gitea
    version: 10.3.0
    repo_url: https://dl.gitea.com/charts
  - name: keycloak
    version: 22.1.0
    repo_url: https://charts.bitnami.com/bitnami
  - name: k10
    version: 7.0.5
    repo_url: https://charts.kasten.io

bootstrap:                                         
  harbor_chart_version: 1.15.1       
  store_path: /tmp/bootstrap
  archive_path: $PWD/bootstrap.tar.zst
