rancher_version: v2.8.2
cert_manager_version: v1.13.2
hauler:
  host: 10.10.0.50
  store_path: /home/deathstar/hauler            #! this is just a local place to store cached store data
  archive_path: /home/deathstar/hauler.tar.zst  #! this file will be one of the artifact copied into your airgap

carbide:
  version: 0.1.1
  chart_repo: https://rancherfederal.github.io/carbide-charts
  airgapped_docs:
    version: 0.1.47
  stigatron:
    version: 0.2.5

additional_charts:
  - name: loki-stack
    version: 2.10.2
    repo_url: https://grafana.github.io/helm-charts
  - name: consul
    version: 0.39.0
    repo_url: https://helm.releases.hashicorp.com
  - name: vault
    version: 0.25.0
    repo_url: https://helm.releases.hashicorp.com
  - name: neuvector
    version: 103.0.2+up2.7.3
    repo_url: https://charts.rancher.io
  - name: neuvector-crd
    version: 103.0.2+up2.7.3
    repo_url: https://charts.rancher.io
  - name: rancher-cis-benchmark
    version: 5.0.0
    repo_url: https://charts.rancher.io
  - name: rancher-cis-benchmark-crd
    version: 5.0.0
    repo_url: https://charts.rancher.io
  - name: rancher-monitoring
    version: 103.0.3+up45.31.1
    repo_url: https://charts.rancher.io
  - name: rancher-monitoring-crd
    version: 103.0.3+up45.31.1
    repo_url: https://charts.rancher.io
  - name: epinio
    version: 103.0.2+up1.10.0
    repo_url: https://charts.rancher.io
  - name: epinio-crd
    version: 103.0.2+up1.10.0
    repo_url: https://charts.rancher.io
  - name: ui-plugin-operator
    version: 103.0.1+up0.2.1
    repo_url: https://charts.rancher.io
  - name: ui-plugin-operator-crd
    version: 103.0.1+up0.2.1
    repo_url: https://charts.rancher.io


harbor:                                         #! most of these values should be easy to discern
  chart_version: 1.13.0                         #! this version should stay put, it maps to the tarball stored in this repo
  core_url: harbor.sienarfleet.systems                    #! before reaching the UI you will need to either make a DNS entry that maps this endpoint or edit /etc/hosts
  notary_url: notary.sienarfleet.systems                  #! ditto ^^^
  store_path: /home/deathstar/harbor-store      #! this is just a local place to store cached store data
  archive_path: /home/deathstar/harbor.tar.zst  #! this file will be one of the artifact copied into your airgap
  affinity_node: fulcrum1                       #! this should match one of your nodes within your K8S cluster