externalURL: https://harbor.myurl.com
harborAdminPassword: "Harbor12345"
imagePullPolicy: IfNotPresent

updateStrategy:
  type: Recreate

expose:
  ingress:
    hosts:
      core: harbor.myurl.com
      notary: notary.myurl.com
  tls:
    enabled: true
    certSource: auto

persistence:
  persistentVolumeClaim:
    registry:
      size: 120Gi
      storageClass: "harvester-longhorn"
    chartmuseum:
      storageClass: "harvester-longhorn"
    jobservice:
      storageClass: "harvester-longhorn"
    database:
      storageClass: "harvester-longhorn"
    redis:
      storageClass: "harvester-longhorn"
    trivy:
      storageClass: "harvester-longhorn"
trivy:
  enabled: true
  image:
    # repository the repository for Trivy adapter image
    repository: goharbor/trivy-adapter-photon
    # tag the tag for Trivy adapter image
    tag: v2.9.0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: harbor-cache
            operator: In
            values:
            - "true"   


# If using an external Postgres DB
database:
  type: internal
  internal:
    image:
      repository: goharbor/harbor-db
      tag: v2.9.0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: harbor-cache
            operator: In
            values:
            - "true"   

#   external:
#     host: "postgres.example.com"
#     port: "5432"
#     username: "example-user"
#     password: "example-password"
#     coreDatabase: "registry"
#     notaryServerDatabase: "notary_server"
#     notarySignerDatabase: "notary_signer"

redis:
  # if external Redis is used, set "type" to "external"
  # and fill the connection information in "external" section
  type: internal
  internal:
    image:
      repository: goharbor/redis-photon
      tag: v2.9.0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: harbor-cache
            operator: In
            values:
            - "true"   
exporter:
  image:
    repository: goharbor/harbor-exporter
    tag: v2.9.0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: harbor-cache
            operator: In
            values:
            - "true"   
portal:
  image:
    repository: goharbor/harbor-portal
    tag: v2.9.0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: harbor-cache
            operator: In
            values:
            - "true"   
core:
  image:
    repository: goharbor/harbor-core
    tag: v2.9.0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: harbor-cache
            operator: In
            values:
            - "true"   
jobservice:
  image:
    repository: goharbor/harbor-jobservice
    tag: v2.9.0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: harbor-cache
            operator: In
            values:
            - "true"   
nginx:
  image:
    repository: goharbor/nginx-photon
    tag: v2.9.0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: harbor-cache
            operator: In
            values:
            - "true"   
registry:
  registry:
    image:
      repository: goharbor/registry-photon
      tag: v2.9.0
  controller:
    image:
      repository: goharbor/harbor-registryctl
      tag: v2.9.0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: harbor-cache
            operator: In
            values:
            - "true"   