#@ load("@ytt:data", "data")
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: hauler-fulcrum-images
spec:
  images: 
  #@ for image in data.values.image_list.split():
  - name: #@ image
  #@ end
